//DISCLAMER! This file contains lots of profanity. These words are not intended to show hate or cause harm, but to create a safe space for people to talk, without hate

module.exports = [
  'fuck',
  'f uck',
  'fu ck',
  'fuc k',
  'f u c k',
  'f  u  c  k  ',
  'f3ck',
  'shit',
  's hit',
  'sh it',
  'shi t',
  'sh1t',
  's h i t',
  'cunt',
  'c unt',
  'cu nt',
  'cun t',
  'nigger',
  'n igger',
  'ni gger',
  'nig ger',
  'nigg er',
  'nigge r',
  'n i g g e r',
  'nigga',
  'n igga',
  'ni gga',
  'nig ga',
  'nigg a',
  'negro',
  'negra',
  'asshole',
  'ass hole',
  'a sshole',
  'as shole',
  'assh ole',
  'bitch',
  'b itch',
  'bi tch',
  'bit ch',
  'bastard',
  'b astard',
  'ba stard',
  'bas tard',
  'bast ard',
  'dick',
  'd ick',
  'di ck',
  'dic k',
  'whore',
  'w hore',
  'wh ore',
  'who re',
  'whor e',
  'slut',
  's lut',
  'sl ut',
  'slu t',
  'faggot',
  'f aggot',
  'fa ggot',
  'fag got',
  'fagg ot',
  'faggo t',
  'cock',
  'c ock',
  'co ck',
  'coc k',
  'prick',
  'p rick',
  'pr ick',
  'pri ck',
  'motherfucker',
  'mother fucker',
  'm otherfucker',
  'mo therfucker',
  'mot herfucker',
  'moth erfucker',
  'mothe rfucker',
  'motherf ucker',
  'motherfu cker',
  'motherfuc ker',
  'motherfuck er',
  'motherfucke r',
  'ass',
  'a ss',
  'as s',
  'bullshit',
  'bull shit',
  'b ullshit',
  'bu llshit',
  'bul lshit',
  'bulls hit',
  'bullsh it',
  'bullshi t',
  'crap',
  'c rap',
  'cr ap',
  'cra p',
  'wanker',
  'w anker',
  'wa nker',
  'wan ker',
  'wank er',
  'wanke r',
  'wank3r',
  'twat',
  't wat',
  'tw at',
  'twa t',
  'arse',
  'a rse',
  'ar se',
  'ars e',
  'kike',
  'k ike',
  'ki ke',
  'kik e',
  'chink',
  'c hink',
  'ch ink',
  'chi nk',
  'chin k',
  'spic',
  's pic',
  'sp ic',
  'spi c',
  'retard',
  'r etard',
  're tard',
  'ret ard',
  'reta rd',
  'retar d',
  'fag',
  'f ag',
  'fa g',
  '🧀',
  'cheese',
  'c heese',
  'ch eese',
  'che ese',
  'chee se',
  'chees e',
  'adolf',
  'a dolf',
  'ad olf',
  'ado lf',
  'adol f',
  'hitler',
  'h itler',
  'hi tler',
  'hit ler',
  'hitl er',
  'hitle r',
  'gas the jews',
  'hittller',
  'gang bang',
  'porn',
  'p orn',
  'po rn',
  'por n',
  'nate higgers',
  'n!ggers',
  'n !ggers',
  'n! ggers',
  'n!g gers',
  'n!gg ers',
  'n!gge rs',
  'n!gger s',
  'prostitute',
  'p rostitute',
  'pr ostitute',
  'pro stitute',
  'pros titute',
  'prost itute',
  'prosti tute',
  'prostit ute',
  'prostitu te',
  'prostitut e',
  'pedo',
  'p edo',
  'pe do',
  'ped o',
  'pedophile',
  'p edophile',
  'pe dophile',
  'ped ophile',
  'pedo phile',
  'pedop hile',
  'pedoph ile',
  'pedophi le',
  'pedophil e',
  'masturbation',
  'm asturbation',
  'ma sturbation',
  'mas turbation',
  'mast urbation',
  'mastu rbation',
  'mastur bation',
  'masturb ation',
  'masturba tion',
  'masturbat ion',
  'masturbati on',
  'masturbatio n',
  '🍆',
  'feck',
  'f eck',
  'fe ck',
  'fec k',
  'fec3',
  'f ec3',
  'fe c3',
  'fec 3',
  'ball licker',
];
