//DISCLAMER! This file contains lots of profanity. These words are not intended to show hate or cause harm, but to create a safe space for people to talk, without hate

module.exports = [
  'fuck',
  'f uck',
  'fu ck',
  'fuc k',
  'f u c k',
  'f  u  c  k  ',
  'f3ck',
  'shit',
  's hit',
  'sh it',
  'shi t',
  'sh1t',
  's h i t',
  'cunt',
  'c unt',
  'cu nt',
  'cun t',
  'nigger',
  'n igger',
  'ni gger',
  'nig ger',
  'nigg er',
  'nigge r',
  'nigga',
  'n igga',
  'ni gga',
  'nig ga',
  'nigg a',
  'asshole',
  'ass hole',
  'a sshole',
  'as shole',
  'assh ole',
  'bitch',
  'b itch',
  'bi tch',
  'bit ch',
  'bastard',
  'b astard',
  'ba stard',
  'bas tard',
  'bast ard',
  'dick',
  'd ick',
  'di ck',
  'dic k',
  'whore',
  'w hore',
  'wh ore',
  'who re',
  'slut',
  's lut',
  'sl ut',
  'slu t',
  'faggot',
  'f aggot',
  'fa ggot',
  'fag got',
  'fagg ot',
  'cock',
  'c ock',
  'co ck',
  'coc k',
  'prick',
  'p rick',
  'pr ick',
  'pri ck',
  'motherfucker',
  'mother fucker',
  'm otherfucker',
  'mo therfucker',
  'mot herfucker',
  'moth erfucker',
  'mothe rfucker',
  'motherf ucker',
  'ass',
  'a ss',
  'as s',
  'bullshit',
  'bull shit',
  'b ullshit',
  'bu llshit',
  'bul lshit',
  'bulls hit',
  'crap',
  'c rap',
  'cr ap',
  'wanker',
  'w anker',
  'wa nker',
  'wan ker',
  'wank3r',
  'twat',
  't wat',
  'tw at',
  'arse',
  'a rse',
  'ar se',
  'kike',
  'k ike',
  'ki ke',
  'chink',
  'c hink',
  'ch ink',
  'spic',
  's pic',
  'sp ic',
  'retard',
  'r etard',
  're tard',
  'ret ard',
  'fag',
  'f ag',
  'fa g',
  '🧀',
  'cheese',
  'adolf',
  'hitler',
  'gas the jews',
  'hittller',
  'gang bang',
  'porn',
  'nate higgers',
  'n!ggers',
  'prostitute',
  'pedo',
  'pedophile',
  'masturbation',
  '🍆',
  'feck',
  'fec3'

];

